config/routes.rb
Rails.application.routes.draw do
  root "categories#index"
  
  resources :rooms do
    resources :messages
  end

    resources :categories do
      resources :products
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  validates :name, presence: true

end

app/models/room.rb
class Room < ApplicationRecord
has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json

  def index
    @category = Category.all
    respond_with(@category)
  end

  def show
    respond_with(@category)
    @products = @category.products
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
    respond_with(@category)
  end

  def create
    @category = Category.new(category_params)
    flash[:notice] = "Category was successfully created" if @category.save
    respond_with(@category)

  end

  def update
    flash[:notice] = 'Category was successfully updated.' if @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    flash[:notice] = 'Category was successfully deleted.'
    respond_with(@category)
  end

  private
  
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_room, only: %i[new create]
  
    def new
      @message = @room.messages.new
    end
  
    def create
      @message = @room.messages.create!(message_params)
      if @message.save
        RoomChannel.broadcast_to(@room, {
          content: @message.content,
          created_at: @message.created_at.strftime('%H:%M')
        })
        
        redirect_to room_path(@room), notice: 'Message sent successfully'
      else
       
        render :new, alert: 'Message could not be sent'
      end
    end
  
    private
  
    def set_room
      @room = Room.find(params[:room_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to rooms_path, alert: 'Room not found'
    end
  
    def message_params
      params.require(:message).permit(:content)
    end
  end
  

app/controllers/products_controller.rb
class ProductsController <ApplicationController
  before_action :set_category
    # def index
    #     @products = @category.products 
    # end

    def show
      @category = Category.find(params[:category_id])
     @product = @category.products.find(params[:id])
      # if @category
      #   @product = @category.products.find(params[:id])
      # else
      #   redirect_to categories_path, alert: "Category not found."
      # end
      end
    
      def new
        @product = @category.products.build
        respond_with(@product)
      end
    
      def create
    
        @category  =Category.find(params[:category_id])
        @product = @category.products.create(product_params)
        redirect_to category_path(@category)
        
      end

      def destroy
        @category = Category.find(params[:category_id])
        @product = @Category.products.find(params[:id])
        @product.destroy
        redirect_to category_path(@category), status: :see_other
      end

    
    
      private
    
      def set_category
        @category = Category.find(params[:category_id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = 'Category not found.'
        
        
      end
    
      def product_params
        params.require(:product).permit(:name) 
      end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/categories/_category.html.slim
.px-3.py-2.rounded-sm.mx-auto id="#{dom_id category}"
.grid.grid-col-3.gap-2[style="width: 12rem;"] 
   .p-2.bg-white.border.border-gray-200.shadow-md.rounded-md
      img.card-img-top[src="https://www.tmaker.my/wp-content/uploads/2022/12/custom-printing-tshirt-design-nho1100-basil.png" alt="Card image cap"]
      .card-body
         p.text-lg.font-semibold.text-center
            = category.title
         a.btn.btn-primary.mx-auto href=category_products_path(category_id: category.id)
            | Show products



   
      
 

app/views/categories/_form.html.slim
= form_with(model: category) do |form|
  - if category.errors.any?
    div style="color: red"
      h2 = "#{pluralize(category.errors.count, "error")} prohibited this category from being saved:"
      ul
        - category.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :description, style: "display: block"
    = form.text_area :description

  div
    = form.submit

app/views/categories/edit.html.slim
h1 Editing category

== render "form", category: @category

br

div
  => link_to "Show this category", @category
  '|
  =< link_to "Back to categories", categories_path

app/views/categories/index.html.slim
p.text-blue-500 = notice

h2.text-blue-500.bg-sky-200 All categories

#categories
  - @category.each do |category|
  
    == render category
   
a.btn.btn-primary.m-3 href=new_category_path
      | New category

app/views/categories/new.html.slim
.container.mt-5
  .row
    .col-md-8.offset-md-2
      .card
        .card-body
          h1.card-title.mb-4.text-center.bg-info.p-3
           New Category

          = render "form", category: @category

          .mt-4.text-center
            = link_to "Back to Categories", categories_path, class: "btn btn-outline-primary btn-lg"

app/views/categories/show.html.slim
p style="color: green" = notice

== render @category

div
  => link_to "Edit this category", edit_category_path(@category)
  '|
  =< link_to "Back to categories", categories_path

  = button_to "Destroy this category", @category, method: :delete

app/views/headers/_header.html.slim
nav.bg-gray-800
  .container.mx-auto.flex.items-center.justify-between.px-4
    .text-white.text-2xl.font-bold
      a href="/" LOGO

    .hidden.md:flex.space-x-4
      a.text-white.hover:bg-gray-700.px-3.py-3.rounded-xl.no-underline[href="/categories/new"]
        | Category
      a.text-white.hover:bg-gray-700.px-3.py-3.rounded-xl.no-underline[href="/rooms"]
        | Rooms
      a.text-white.hover:bg-gray-700.px-3.py-3.rounded-xl.no-underline[href="/"]
        | Home
     

    .md:hidden.flex.items-center
      button.bg-gray-700.text-white.px-3.py-2.rounded
        span.h-6.w-6.block.bg-white
         

    .md:hidden.flex.flex-col.absolute.top-0.left-0.w-full.bg-gray-800.mt-12.text-center
      a.text-white.hover:bg-gray-700.px-3.py-2.rounded-xl.no-underline.mx-5[href="/categories/new"]
        | Category
      a.text-white.hover:bg-gray-700.px-3.py-2.rounded-xl.no-underline.mx-5[href="/rooms"]
        | Rooms
      a.text-white.hover:bg-gray-700.px-3.py-2.rounded-xl.no-underline.mx-5[href="/"]
        | Home
      a.text-white.hover:bg-gray-700.px-3.py-2.rounded-xl.no-underline.mx-5[href="#"]
        | Another

      

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for(:title) || "Project"
    meta name="viewport" content="width=device-width,initial-scale=1"
    meta name="apple-mobile-web-app-capable" content="yes"
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link rel="manifest" href="/manifest.json"
    link rel="icon" href="/icon.png" type="image/png"
    link rel="icon" href="/icon.svg" type="image/svg+xml"
    link rel="apple-touch-icon" href="/icon.png"
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

  body
    = render 'headers/header'
    .container
      = yield

app/views/messages/_form.html.slim
= form_with(model: [@room, @message], local: true) do |form|
  .field
    = form.label :content
    = form.text_area :content, rows: 4
  .actions
    = form.submit 'Create Message'

app/views/messages/_message.html.slim
#message
  p
    strong message Content:
    =< message.content
    strong
    =< message.created_at.strftime('%H:%M') %>:

app/views/messages/new.html.slim
h1 New message

== render "form", message: @message

app/views/products/_form.html.slim
h5 Add product

= form_with model: [ @category, @category.products.build ] do |form|
  p
    = form.label :name
    br
    = form.text_field :name
  .container
    p.bg-blue-300.px-3.py-2.rounded-xl.hover:bg-blue-400.mx-auto.text-center
      = form.submit 

app/views/products/_product.html.slim
.div.px-3.py-2.rounded-sm.mx-auto
  .grid.grid-cols-3.gap-3
    - @category.products.each do |product|
      .p-2.bg-white.border.border-gray-200.shadow-md.rounded-md
        .bg-cover.bg-center
          - image_url = "https://cdn.pgmall.my/image/cache/catalog/seller_store/store23467/product/0072302001656125072da43a6e437fd4c299c9848671cf5d491-400x400.jpg"
          .h-40.bg-cover.bg-center(style="background-image: url('#{image_url}');")
        .px-2.py-3.mx-auto
          p.text-lg.font-semibold.text-center
            = product.name
      
            

app/views/products/index.html.slim
h2.bg-blue.text-center.py-4.px-3.rounded-xl Product 
= render @category.products

.container 
= render "products/form", category: @category

app/views/products/new.html.slim
= form_with(model: [@category, @product], local: true) do |f|
  - if @product.errors.any?
    .error-messages
      h2
        | = pluralize(@product.errors.count, "error") prohibited this product from being saved:
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .actions
    = f.submit 'Create Product', class: 'btn btn-primary'
    
= link_to 'Back to Category', category_path(@category), class: 'btn btn-secondary'

app/views/products/show.html.slim
h2 Comments

- @category.products.each do |product|
  p
    strong name:
    = product.name

app/views/rooms/_form.html.slim
= form_with(model: room) do |form|
  - if room.errors.any?
    div style="color: red"
      h2 = "#{pluralize(room.errors.count, "error")} prohibited this room from being saved:"
      ul
        - room.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.submit

app/views/rooms/_room.html.slim
#room
  p
    strong Name:
    =< room.name

app/views/rooms/edit.html.slim
h1 Editing room

== render "form", room: @room

br

div
  => link_to "Show this room", @room
  '|
  =< link_to "Back to rooms", rooms_path

app/views/rooms/index.html.slim
p style="color: green" = notice

h1 Rooms

#potato
  #rooms
    - @rooms.each do |room|
      == render room
      p
        = link_to "Show this room", room

  = link_to "New room", new_room_path

app/views/rooms/new.html.slim
h1 New room

== render "form", room: @room

br

div
  = link_to "Back to rooms", rooms_path

app/views/rooms/show.html.slim
p style="color: green" = notice


#potato
  == render @room
  div
  => link_to "Edit this room", edit_room_path(@room)
  '|
  =< link_to "Back to rooms", rooms_path

  = button_to "Destroy this room", @room, method: :delete



   
h2 Messages
ul
  - @room.messages.each do |message|
    li
      | #{message.content}
  

div
  = link_to "New message", new_room_message_path(@room)